services:
  posterizarr:
#    hostname: posterizarr
    container_name: posterizarr
    env_file:
      - .env
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TERM=xterm
      - RUN_TIME=disabled
      # OPTIONAL: This tells uvicorn to run on port 9000 inside the container
      #- APP_PORT=9000      
      # OPTIONAL: Disable UI
      #- DISABLE_UI=true   
    image: ghcr.io/fscorrupt/posterizarr:latest
    restart: unless-stopped
#    user: 1000:1000
    ports:
      - 8181:8000 # if you want to change the port inside container, also change APP_PORT env variable
    network_mode: "bridge"
#    networks:
#      - proxy
    volumes:
      - /docker/posterizarr:/config:rw
      - /docker/posterizarr/assets:/assets:rw
      - /docker/posterizarr/assetsbackup:/assetsbackup:rw
      - /docker/posterizarr/manualassets:/manualassets:rw