services:
  lingarr:
    image: lingarr/lingarr:1.3.0
    container_name: lingarr
    environment:
      - TZ=${TZ}
      - ASPNETCORE_URLS=http://+:9876
      - DB_CONNECTION=${DB_CONNECTION}
    volumes:
      - ${MOVIEDIR}:/filme
      - ${TVDIR}:/serien
      - ${LINGARR_CONFIG}:/app/config
    ports:
      - ${LINGARR_PORT}:9876
    network_mode: bridge
    restart: unless-stopped
